---
version: '3'
services:
  app:
    build: .
    ports:
    - "8000:5000"
    restart: always
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/hanggiamgia
    links:
    - db

  db:
    image: "postgres:13-alpine"
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hanggiamgia
    ports:
    - "5432:5432"
