"""added report reasons

Revision ID: 347fa9cc837b
Revises: 3e9f466be54e
Create Date: 2021-01-10 17:53:26.170251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347fa9cc837b'
down_revision = '3e9f466be54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reasons')
    # ### end Alembic commands ###
