"""added images table

Revision ID: 36bf76f3cd9c
Revises: f3005bd87c37
Create Date: 2020-12-31 21:17:17.091782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bf76f3cd9c'
down_revision = 'f3005bd87c37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_author'), 'images', ['author'], unique=False)
    op.add_column('posts', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_url')
    op.drop_index(op.f('ix_images_author'), table_name='images')
    op.drop_table('images')
    # ### end Alembic commands ###
