"""added relationship between reports and reasons table

Revision ID: c2360c73989e
Revises: 395c8faf7b3a
Create Date: 2021-01-10 22:31:29.265766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2360c73989e'
down_revision = '395c8faf7b3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'reason_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'reports', 'reasons', ['reason_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.alter_column('reports', 'reason_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
